export const MOCK_OPTION_THEMES = [
  {
    isImage: true,
    id: '12',
    nameIcon: 'software',
    title: 'Software',
    value: 'software',
  },
  {
    isImage: false,
    id: '23',
    nameIcon: 'cpu',
    title: 'Technology',
    value: 'technology',
  },
  {
    isImage: true,
    id: '34',
    nameIcon: 'food&drink',
    title: 'Food & Drink',
    value: 'food_&_drink',
  },
  {
    isImage: true,
    id: '45',
    nameIcon: 'network',
    title: 'Business',
    value: 'bussiness',
  },
  {
    isImage: true,
    id: '56',
    nameIcon: 'sports',
    title: 'Sports',
    value: 'sports',
  },
  {
    isImage: true,
    id: '78',
    nameIcon: 'eCommerce',
    title: 'eCommerce',
    value: 'ecomerce',
  },
  {
    isImage: false,
    id: '88',
    nameIcon: 'trending-up',
    title: 'Stock exchange',
    value: 'stock_exchange',
  },
  {
    isImage: true,
    id: '99',
    nameIcon: 'fintech',
    title: 'Fintech',
    value: 'fintech',
  },
];
